### PR TITLE
Extra Fizzlers

### PR DESCRIPTION
**Pull request by TheDarkBomber**
Closed Solid Field and Physics Shield.

### CODE REVIEW

**Comment by TeamSpen210** [comment]
This needs some style variants first... Additionally the 'physler' was made by Felix Griffin, not FourthReaper.

**Comment by ZombiePwner1** [comment]
Alright I will revert it.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - If you haven´t enough knowledge about the funtionallity from this site and its features, id recommend to not touch anything related to the mod´s stuff.

In my personal case, i am still a noob, and the only advantage i take from being a collaborator is only to add lavels to my post.

**Comment by ZombiePwner1** [comment]
I'm gonna see if @TeamSpen210 can teach me how to do that stuff when I get home.

**Comment by TheDarkBomber** [comment]
It was made by FourthReaper, according to the Valve Developer Wiki.

**Comment by TeamSpen210** [comment]
It's made by [Felix Griffin](https://developer.valvesoftware.com/wiki/Physler).

**Comment by TheDarkBomber** [comment]
[FourthReaper](https://developer.valvesoftware.com/wiki/Modified_Fizzler_Fields).

**Comment by TeamSpen210** [comment]
That page is misleading, originally it only listed the 1st 4 (which are made by Fourthreaper). The others are not. (Felix, LPFreaky, Felix in order). I'll have to edit the page.

**Pull request merged**
